### ISSUE TITLE
java.lang.NoSuchMethodError with ring 1.71 and figwheel 0.2.1

### ISSUE THREAD

**Issue by AndreaCrotti** [cognitect-labs/aws-api#83] opened 2019-06-26 09:51 UTC
## Dependencies
These are the relevant dependencies to reproduce the problem:

[ring "1.7.1"]
[com.bhauman/figwheel-main "0.2.1"]
[org.eclipse.jetty/jetty-server "9.4.19.v20190610"]
[org.eclipse.jetty/jetty-util "9.4.19.v20190610"]
[com.cognitect.aws/api "0.8.305"]
[com.cognitect.aws/endpoints "1.1.11.568"]
[com.cognitect.aws/s3 "722.2.468.0"]

The jetty ones were added to make ring and figwheel-main both work, which however seems to break this library.

## Description with failing test case

I'm trying to use the S3 library, and it fails even with something as simple as:

```
(def c (s3-client))

(aws/invoke c {:op :ListBuckets})
```

I suppose it's because this newer jetty client library is not supported yet, is that correct?

Any other suggestions about how to make figwheel-main/ring and aws-api work together nicely?

## Stack traces

```
{:cognitect.anomalies/category :cognitect.anomalies/fault, :cognitect.anomalies/message "org.eclipse.jetty.io.SelectorManager.connect(Ljava/nio/channels/SocketChannel;Ljava/lang/Object;)V", :cognitect.http-client/throwable #error {
 :cause "org.eclipse.jetty.io.SelectorManager.connect(Ljava/nio/channels/SocketChannel;Ljava/lang/Object;)V"
 :via
 [{:type java.lang.NoSuchMethodError
   :message "org.eclipse.jetty.io.SelectorManager.connect(Ljava/nio/channels/SocketChannel;Ljava/lang/Object;)V"
   :at [org.eclipse.jetty.client.AbstractHttpClientTransport connect "AbstractHttpClientTransport.java" 118]}]
 :trace
 [[org.eclipse.jetty.client.AbstractHttpClientTransport connect "AbstractHttpClientTransport.java" 118]
  [org.eclipse.jetty.client.HttpClient$1 connect "HttpClient.java" 580]
  [org.eclipse.jetty.client.HttpClient$1 access$100 "HttpClient.java" 545]
  [org.eclipse.jetty.client.HttpClient$1$1 failed "HttpClient.java" 577]
  [org.eclipse.jetty.client.AbstractHttpClientTransport connectFailed "AbstractHttpClientTransport.java" 152]
  [org.eclipse.jetty.client.AbstractHttpClientTransport connect "AbstractHttpClientTransport.java" 141]
  [org.eclipse.jetty.client.HttpClient$1 connect "HttpClient.java" 580]
  [org.eclipse.jetty.client.HttpClient$1 succeeded "HttpClient.java" 551]
  [org.eclipse.jetty.client.HttpClient$1 succeeded "HttpClient.java" 545]
  [org.eclipse.jetty.util.SocketAddressResolver$Async lambda$resolve$1 "SocketAddressResolver.java" 181]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 781]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$Runner run "QueuedThreadPool.java" 917]
  [java.lang.Thread run "Thread.java" 748]]}}
```

**Comment by dchelimsky** [comment] 2019-07-01 03:03
The next release will use `http-client` 0.1.99, which uses jetty 9.4 (upgrade from 9.3), so this should go away. Leaving this open until it does.

**Comment by dchelimsky** [comment] 2019-07-01 13:11
Not sure what's different about our environments, but I can't reproduce the error you're seeing using the same versions you're using:

```
$ clj -Sdeps '{:deps {ring {:mvn/version "1.7.1"}
com.bhauman/figwheel-main {:mvn/version "0.2.1"}
org.eclipse.jetty/jetty-server {:mvn/version "9.4.19.v20190610"}
org.eclipse.jetty/jetty-util {:mvn/version "9.4.19.v20190610"}
com.cognitect.aws/api {:mvn/version "0.8.305"}
com.cognitect.aws/endpoints {:mvn/version "1.1.11.568"}
com.cognitect.aws/s3 {:mvn/version "722.2.468.0"}}}'
Clojure 1.10.1
user=> (require '[cognitect.aws.client.api :as aws])
nil
user=> (def c (aws/client {:api :s3}))
2019-07-01 08:05:40.939:INFO::main: Logging initialized @17038ms to org.eclipse.jetty.util.log.StdErrLog
#'user/c
user=> (aws/invoke c {:op :ListBuckets})
{:Buckets [<elided>]}
```

**Comment by AndreaCrotti** [comment] 2019-07-01 13:17
Uhm that's true, I have to check all the transitive deps to see if it's something else maybe then affecting it. (I also use lein instead of clj but it should not matter)

**Comment by dchelimsky** [comment] 2019-07-01 13:22
Here is the class path I get using the same command + `-Spath` (sorry it's so noisy, but maybe this will help you figure out the differences:

```
src:/Users/david/.m2/repository/com/cognitect/transit-java/0.8.332/transit-java-0.8.332.jar:/Users/david/.m2/repository/org/clojure/data.json/0.2.6/data.json-0.2.6.jar:/Users/david/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar:/Users/david/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar:/Users/david/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/Users/david/.m2/repository/com/cognitect/aws/api/0.8.305/api-0.8.305.jar:/Users/david/.m2/repository/org/clojure/tools.analyzer/0.6.9/tools.analyzer-0.6.9.jar:/Users/david/.m2/repository/com/bhauman/cljs-test-display/0.1.1/cljs-test-display-0.1.1.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-xml/9.4.12.v20180830/jetty-xml-9.4.12.v20180830.jar:/Users/david/.m2/repository/com/bhauman/figwheel-repl/0.2.1/figwheel-repl-0.2.1.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-servlet/9.4.12.v20180830/jetty-servlet-9.4.12.v20180830.jar:/Users/david/.m2/repository/ring/ring-devel/1.7.1/ring-devel-1.7.1.jar:/Users/david/.m2/repository/com/cognitect/aws/endpoints/1.1.11.568/endpoints-1.1.11.568.jar:/Users/david/.m2/repository/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar:/Users/david/.m2/repository/org/clojure/tools.logging/0.4.0/tools.logging-0.4.0.jar:/Users/david/.m2/repository/org/clojure/core.specs.alpha/0.2.44/core.specs.alpha-0.2.44.jar:/Users/david/.m2/repository/co/deps/ring-etag-middleware/0.2.0/ring-etag-middleware-0.2.0.jar:/Users/david/.m2/repository/expound/expound/0.7.1/expound-0.7.1.jar:/Users/david/.m2/repository/org/clojure/spec.alpha/0.2.176/spec.alpha-0.2.176.jar:/Users/david/.m2/repository/commons-fileupload/commons-fileupload/1.3.3/commons-fileupload-1.3.3.jar:/Users/david/.m2/repository/com/bhauman/figwheel-main/0.2.1/figwheel-main-0.2.1.jar:/Users/david/.m2/repository/ring/ring-ssl/0.3.0/ring-ssl-0.3.0.jar:/Users/david/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-http/9.4.19.v20190610/jetty-http-9.4.19.v20190610.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-util/9.4.19.v20190610/jetty-util-9.4.19.v20190610.jar:/Users/david/.m2/repository/org/clojure/tools.analyzer.jvm/0.7.2/tools.analyzer.jvm-0.7.2.jar:/Users/david/.m2/repository/net/incongru/watchservice/barbary-watchservice/1.0/barbary-watchservice-1.0.jar:/Users/david/.m2/repository/ring-cors/ring-cors/0.1.12/ring-cors-0.1.12.jar:/Users/david/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/Users/david/.m2/repository/ring/ring-defaults/0.3.2/ring-defaults-0.3.2.jar:/Users/david/.m2/repository/org/clojure/google-closure-library/0.0-20170809-b9c14c6b/google-closure-library-0.0-20170809-b9c14c6b.jar:/Users/david/.m2/repository/org/clojure/clojurescript/1.10.339/clojurescript-1.10.339.jar:/Users/david/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.4.12.v20180830/websocket-api-9.4.12.v20180830.jar:/Users/david/.m2/repository/ring/ring-jetty-adapter/1.7.1/ring-jetty-adapter-1.7.1.jar:/Users/david/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/Users/david/.m2/repository/org/clojure/tools.namespace/0.2.11/tools.namespace-0.2.11.jar:/Users/david/.m2/repository/com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotations-1.0.0.jar:/Users/david/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.4.12.v20180830/websocket-client-9.4.12.v20180830.jar:/Users/david/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar:/Users/david/.m2/repository/clj-time/clj-time/0.14.3/clj-time-0.14.3.jar:/Users/david/.m2/repository/org/eclipse/jetty/websocket/websocket-servlet/9.4.12.v20180830/websocket-servlet-9.4.12.v20180830.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-security/9.4.12.v20180830/jetty-security-9.4.12.v20180830.jar:/Users/david/.m2/repository/org/mozilla/rhino/1.7R5/rhino-1.7R5.jar:/Users/david/.m2/repository/ring/ring-headers/0.3.0/ring-headers-0.3.0.jar:/Users/david/.m2/repository/org/clojure/google-closure-library-third-party/0.0-20170809-b9c14c6b/google-closure-library-third-party-0.0-20170809-b9c14c6b.jar:/Users/david/.m2/repository/hiccup/hiccup/1.0.5/hiccup-1.0.5.jar:/Users/david/.m2/repository/binaryage/env-config/0.2.2/env-config-0.2.2.jar:/Users/david/.m2/repository/com/cognitect/http-client/0.1.87/http-client-0.1.87.jar:/Users/david/.m2/repository/com/google/javascript/closure-compiler-externs/v20180610/closure-compiler-externs-v20180610.jar:/Users/david/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar:/Users/david/.m2/repository/org/clojure/java.classpath/0.2.3/java.classpath-0.2.3.jar:/Users/david/.m2/repository/ns-tracker/ns-tracker/0.3.1/ns-tracker-0.3.1.jar:/Users/david/.m2/repository/com/google/guava/guava/22.0/guava-22.0.jar:/Users/david/.m2/repository/binaryage/devtools/0.9.10/devtools-0.9.10.jar:/Users/david/.m2/repository/org/msgpack/msgpack/0.6.12/msgpack-0.6.12.jar:/Users/david/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/david/.m2/repository/com/cognitect/transit-clj/0.8.309/transit-clj-0.8.309.jar:/Users/david/.m2/repository/args4j/args4j/2.33/args4j-2.33.jar:/Users/david/.m2/repository/crypto-random/crypto-random/1.2.0/crypto-random-1.2.0.jar:/Users/david/.m2/repository/ring/ring-codec/1.1.1/ring-codec-1.1.1.jar:/Users/david/.m2/repository/ring/ring-anti-forgery/1.3.0/ring-anti-forgery-1.3.0.jar:/Users/david/.m2/repository/com/bhauman/spell-spec/0.1.1/spell-spec-0.1.1.jar:/Users/david/.m2/repository/crypto-equality/crypto-equality/1.0.0/crypto-equality-1.0.0.jar:/Users/david/.m2/repository/net/java/dev/jna/jna/3.2.2/jna-3.2.2.jar:/Users/david/.m2/repository/com/bhauman/figwheel-core/0.2.1/figwheel-core-0.2.1.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-client/9.4.12.v20180830/jetty-client-9.4.12.v20180830.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-io/9.4.19.v20190610/jetty-io-9.4.19.v20190610.jar:/Users/david/.m2/repository/org/clojure/tools.reader/1.3.0-alpha3/tools.reader-1.3.0-alpha3.jar:/Users/david/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/david/.m2/repository/com/cognitect/aws/s3/722.2.468.0/s3-722.2.468.0.jar:/Users/david/.m2/repository/clj-stacktrace/clj-stacktrace/0.2.8/clj-stacktrace-0.2.8.jar:/Users/david/.m2/repository/com/google/javascript/closure-compiler-unshaded/v20180610/closure-compiler-unshaded-v20180610.jar:/Users/david/.m2/repository/org/eclipse/jetty/websocket/websocket-server/9.4.12.v20180830/websocket-server-9.4.12.v20180830.jar:/Users/david/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.4.12.v20180830/websocket-common-9.4.12.v20180830.jar:/Users/david/.m2/repository/com/google/protobuf/protobuf-java/3.0.2/protobuf-java-3.0.2.jar:/Users/david/.m2/repository/ring/ring-servlet/1.7.1/ring-servlet-1.7.1.jar:/Users/david/.m2/repository/org/clojure/core.memoize/0.5.9/core.memoize-0.5.9.jar:/Users/david/.m2/repository/hawk/hawk/0.2.11/hawk-0.2.11.jar:/Users/david/.m2/repository/ring/ring/1.7.1/ring-1.7.1.jar:/Users/david/.m2/repository/org/clojure/data.priority-map/0.0.7/data.priority-map-0.0.7.jar:/Users/david/.m2/repository/org/eclipse/jetty/jetty-server/9.4.19.v20190610/jetty-server-9.4.19.v20190610.jar:/Users/david/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar:/Users/david/.m2/repository/ring/ring-core/1.7.1/ring-core-1.7.1.jar:/Users/david/.m2/repository/org/clojure/core.cache/0.6.5/core.cache-0.6.5.jar:/Users/david/.m2/repository/org/ow2/asm/asm-all/4.2/asm-all-4.2.jar:/Users/david/.m2/repository/org/clojure/core.async/0.4.490/core.async-0.4.490.jar:/Users/david/.m2/repository/com/google/code/gson/gson/2.7/gson-2.7.jar
```

**Comment by dchelimsky** [comment] 2019-07-05 13:13
Closing this since given I can't reproduce it. Feel free to keep chatting here and I'll reopen it if it's something we need to fix.

**Closed by dchelimsky** 2019-07-05 13:13 UTC
Labels: bug, cannot reproduce
