### ISSUE TITLE
Could not locate clojure/data/xml__init.class, clojure/data/xml.clj or clojure/data/xml.cljc on classpath

### ISSUE THREAD

**Issue by cjsauer** [cognitect-labs/aws-api#86] opened 2019-07-06 17:05 UTC
## Dependencies

``` clojure
        com.cognitect.aws/api                        {:mvn/version "0.8.342"}
        com.cognitect.aws/endpoints                  {:mvn/version "1.1.11.568"}
        com.cognitect.aws/email                      {:mvn/version "722.2.470.0"}
        com.cognitect.aws/sns                        {:mvn/version "718.2.444.0"}
        com.cognitect.aws/pinpoint                   {:mvn/version "711.2.411.0"}
```

## Description with failing test case

Started running into this error while attempting to deploy via Datomic Ions after upgrading to `0.8.342` (although I believe the offending release is `0.8.335`, in which a switch was made from `clojure.xml` to `clojure.data.xml`). Including an explicit dependency on `clojure.data.xml` does not fix the issue. 

## Stack traces

Here is an abbreviated stack trace from CloudWatch logs:

```
"Type": "clojure.lang.ExceptionInfo",
                "Message": "Syntax error compiling at (cognitect/aws/util.clj:1:1).",
                "Data": {
                    "CognitectAnomaliesCategory": "CognitectAnomaliesFault",
                    "DatomicAnomaliesException": {
                        "Via": [
                            {
                                "Type": "clojure.lang.Compiler$CompilerException",
                                "Message": "Syntax error compiling at (cognitect/aws/util.clj:1:1).",
                                "Data": {
                                    "ClojureErrorPhase": "CompileSyntaxCheck",
                                    "ClojureErrorLine": 1,
                                    "ClojureErrorColumn": 1,
                                    "ClojureErrorSource": "cognitect/aws/util.clj"
                                },
                                "At": [
                                    "clojure.lang.Compiler",
                                    "load",
                                    "Compiler.java",
                                    7647
                                ]
                            },
                            {
                                "Type": "java.io.FileNotFoundException",
                                "Message": "Could not locate clojure/data/xml__init.class, clojure/data/xml.clj or clojure/data/xml.cljc on classpath.",
                                "At": [
                                    "clojure.lang.RT",
                                    "load",
                                    "RT.java",
                                    466
                                ]
                            }
                        ],
```

**Comment by cjsauer** [comment] 2019-07-06 17:08
Does tools.deps integrate with lein? It appears that `clojure.data.xml` does not include a deps.edn file, would this cause transitive dependencies to fail to be downloaded?

**Comment by dchelimsky** [comment] 2019-07-06 17:39
I can't explain why adding an explicit dep doesn't resolve it, but the issue is that I failed to update the pom (nothing to do w/ tools.deps or lein).

Fix coming soon.

**Comment by cjsauer** [comment] 2019-07-06 17:40
@dchelimsky ah okay, appreciate the quick response.

**Comment by dchelimsky** [comment] 2019-07-06 17:50
Fixed in 6835cb606df18c16ee8b75e38b8833e70b627e1c

**Comment by dchelimsky** [comment] 2019-07-06 19:10
Released in 0.8.345

**Closed by dchelimsky** 2019-07-06 19:10 UTC
Labels: bug

**Comment by Nolan330** [comment] 2019-07-26 04:51
This issue seems to have mutated in `com.cognitect.aws/api {:mvn/version "0.8.345"}`.

`0.8.305` is the last version that works for our application. `0.8.335` and `0.8.342` both cause the exception as described in the issue. `0.8.345` causes calls to `aws/invoke` to return the following:
```
{:cognitect.anomalies/category :cognitect.anomalies/fault, :cognitect.aws.client/throwable #error {
 :cause "clojure.data.xml$parse"
 :via [{:type java.lang.NoClassDefFoundError
          :message "clojure/data/xml$parse"
          :at [cognitect.aws.util$xml_read invokeStatic "util.clj" 137]}
        {:type java.lang.ClassNotFoundException
         :message "clojure.data.xml$parse"
         :at [java.net.URLClassLoader findClass "URLClassLoader.java" 382]}]
 :trace [[java.net.URLClassLoader findClass "URLClassLoader.java" 382] ...]
```
I'm not sure if it will have any impact, but this is in Java 8. Let me know if I can provide any additional information, or if you'd like me to open a new issue. Otherwise `0.8.305` works well for us!

**Comment by dchelimsky** [comment] 2019-07-26 13:18
@Nolan330 I can use "0.8.345" with java 8 without seeing this.

```
$ java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
$ clj -Sdeps '{:deps
               {com.cognitect.aws/api       {:mvn/version "0.8.345"}
               com.cognitect.aws/endpoints {:mvn/version "1.1.11.592"}
               com.cognitect.aws/s3        {:mvn/version "726.2.488.0"}}}'
>              {com.cognitect.aws/api       {:mvn/version "0.8.345"}
>               com.cognitect.aws/endpoints {:mvn/version "1.1.11.592"}
>               com.cognitect.aws/s3        {:mvn/version "726.2.488.0"}}}'
Clojure 1.10.1
user=> user=> (require '[cognitect.aws.client.api :as aws])
nil
user=> (def c (aws/client {:api :s3}))
#'user/c
user=> (aws/invoke c {:op :ListBuckets})
{:Buckets [{:Name "..."}] :Owner {...}}
```

I wonder what's different about our environments.

**Comment by Nolan330** [comment] 2019-07-26 19:22
Really appreciate the response @dchelimsky. I'm not sure what's happening either.

For additional information, the failing code is running in a java8 lambda. I narrowed down the issue to merely changing `0.8.305` to `0.8.345`; the former runs great, the latter causes the `NoClassDefFoundError`. I'm thinking it's some form of dependency conflict being introduced. I'll check the classpath to see what else is in there.

Let me know if you have any ideas on debugging this beyond inspecting the classpath—something like a `lein deps :tree` or equivalent. Thanks again for your quick response!
