### ISSUE TITLE
Threads created by `aws/client` are never cleaned up

### ISSUE THREAD

**Issue by levand** [cognitect-labs/aws-api#80] opened 2019-06-06 15:12 UTC
Invoking `cognitect.aws.client.api/client` causes the underlying HTTP library to create a pool of ~9 threads (which seems excessive itself, but that's a different issue). These are never released, even when the returned client object goes out of scope. 

Eventually, in applications that make repeated calls to `client`, the JVM will hit the OS limit on thread creation and crash.

Workaround: memoize invocations of the `client` function, or otherwise ensure that the `client` function isn't invoked more than once for each service.

**Comment by thenonameguy** [comment] 2019-06-25 15:36
This is a major problem for us, this has caused thousands of threads to be created:
<img width="249" alt="Screen Shot 2019-06-25 at 1 52 17 PM" src="https://user-images.githubusercontent.com/2217181/60112223-b546f080-976f-11e9-93cd-641e9f506003.png">
<img width="270" alt="Screen Shot 2019-06-25 at 1 52 02 PM" src="https://user-images.githubusercontent.com/2217181/60112224-b546f080-976f-11e9-8059-398516d671fb.png">

We will be working on replacing the internal http client with ours as mentioned:
https://github.com/cognitect-labs/aws-api/issues/82#issuecomment-504392660

**Comment by thenonameguy** [comment] 2019-06-27 15:46
Even with the above PR we were seeing a constant increase of threads, after some digging I found the cause:
https://github.com/cognitect-labs/aws-api/blob/c127044c282b74abb3c3c2a3ad12fe60432a039f/src/cognitect/aws/ec2_metadata_utils.clj#L56

Since the credentials are being refetched this causes a nice constant rate of threads:
<img width="1378" alt="Screen Shot 2019-06-27 at 5 44 56 PM" src="https://user-images.githubusercontent.com/2217181/60280534-67fb8800-9903-11e9-8b66-0cd7f02961b5.png">

**Comment by dchelimsky** [comment] 2019-07-05 13:59
@thenonameguy thanks for digging out the metadata utils issue. We'll definitely address that (probably in the next release). As for the rest, [we don't accept PRs for this project](https://github.com/cognitect-labs/aws-api#contributing). We are currently working on an interface to supply your own http client, and we do plan to address some of the other issues your PR deals with.

**Comment by dchelimsky** [comment] 2019-07-05 17:47
@levand there is already a `cognitect.aws.client.api/stop` fn that shuts down resources on an aws-api client (and its underlying http-client). This was broken due to the bug that @thenonameguy fished out (see comments above), but will be fixed in the coming release. Additionally, we're adding a `default-http-client` fn that you can use to create an http-client and then pass it to the constructor of each of your aws-api clients in order to share a single client. We didn't want to do that implicitly because we want you to able to tune this as you like (e.g. you may want to 5 clients, each with their own underlying http-client, but not 50).

**Comment by dchelimsky** [comment] 2019-07-05 19:43
Fixed in 0.8.335.

**Closed** 2019-07-05 19:42 UTC
Labels: bug, http-client
