### ISSUE TITLE
Dynamodb com.amazon.coral.validate#ValidationException

### ISSUE THREAD

**Issue by tomthought** [cognitect-labs/aws-api#69] opened 2019-04-12 05:57 UTC
Hi all,

I've been trying to get the dynamodb client working and I can't seem to figure out what I'm doing wrong. I'm running dynamodb locally, though the same issue occurs when running remotely.

I'm running the following:
```clojure
(let [client (aws/client
                (merge
                 {:api :dynamodb
                  :credentials-provider (credentials/profile-credentials-provider "my_local_profile")
                  :region-provider (region/profile-region-provider "my_local_profile")
                  :endpoint-override
                  {:protocol :http
                   :hostname "localhost"
                   :port 8000}}))
        table-name "Users"]
    (aws/invoke
     client
     {:op :CreateTable
      :request {:TableName table-name
                :BillingMode "PAY_PER_REQUEST"
                :AttributeDefinitions
                [{:AttributeName "id"
                  :AttributeType "S"}]
                :KeySchema
                [{:AttributeName "id"
                  :KeyType "HASH"}]}})
    (aws/invoke
     client
     {:op :PutItem
      :request {:TableName table-name
                :Item {"id" {"S" "user_number_1"}
                       "name" {"S" "Tom"}}}}))
```

And the output error message:
```clojure
{:__type "com.amazon.coral.validate#ValidationException",
 :message
 "Supplied AttributeValue is empty, must contain exactly one of the supported datatypes",
 :cognitect.anomalies/category :cognitect.anomalies/incorrect}
```

I've searched and all I can find are folks telling me it's either an empty value (both values are populated?) or a schema mismatch (am I providing my key incorrectly? It passes the :PutItem spec). Is there a way to get the output right before the request is put on the wire?

Thanks,
Tom

**Comment by dchelimsky** [comment] 2019-04-12 13:19
I'm not sure this is it, but it looks like you're trying to put a "name" attribute that you haven't defined.

**Comment by dchelimsky** [comment] 2019-04-12 13:21
As for getting the output, you can see the request and response of the last `aws/invoke` invocation with `(meta *1)`.

**Comment by dchelimsky** [comment] 2019-04-12 13:30
Additional datapoint, I just tried `:PutItem` to a table that doesn't exist and got exactly the same error message. I'm closing this because I think it's not an issue with aws-api, but feel free to continue the conversation here and I'll try my best to help you sort it out.

**Closed by dchelimsky** 2019-04-12 13:30 UTC

**Comment by tomthought** [comment] 2019-04-13 00:37
Hey David, 

I've added some print statements into a locally cloned version of the aws-api to try and see what's going on. This one is on line ~70 of aws/client.clj

<img width="651" alt="Screen Shot 2019-04-12 at 8 33 13 PM" src="https://user-images.githubusercontent.com/14667764/56072177-3e01e300-5d62-11e9-874d-eee382e8febc.png">

Where I get this output:

<img width="495" alt="Screen Shot 2019-04-12 at 8 34 02 PM" src="https://user-images.githubusercontent.com/14667764/56072190-570a9400-5d62-11e9-9ff3-e43ffbffa978.png">

Before it gets to the ```clojure build-http-request ``` function everything seems to be in tact, and then that function clobbers the values. Is there a way I can get access to the dynamodb api somewhere so I can start digging through that as well?

As far as I can tell my request is syntactically correct (https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html), and it passes the PutItem spec on your end. Can't think of any reason why the values would be coerced to empty maps?

Thanks for the help so far!

**Comment by tomthought** [comment] 2019-05-06 10:53
Hey @dchelimsky, any chance you're able to get this working on your end? I'm a little lost still as to why it's breaking.

I've even taken the table example you guys have provided and enhanced it with a PutItem call. I get the same issue.

```clojure
(let [ddb (aws/client
             (merge
              {:api :dynamodb
               :credentials-provider (credentials/profile-credentials-provider "my-aws-profile")
               :region-provider (region/profile-region-provider "my-aws-profile")
               :endpoint-override
               {:protocol :http
                :hostname "localhost"
                :port 8000}}))]
    (aws/invoke ddb
                {:op      :CreateTable
                 :request {:TableName             "Forum"
                           :AttributeDefinitions  [{:AttributeName "Name"
                                                    :AttributeType "S"}]
                           :KeySchema             [{:AttributeName "Name"
                                                    :KeyType       "HASH"}]
                           :ProvisionedThroughput {:ReadCapacityUnits  1
                                                   :WriteCapacityUnits 1}}})
    (aws/invoke
     ddb
     {:op :PutItem
      :request {:TableName "Forum"
                :Item {"Name" {"S" "Tom"}}}}))
```

I'm thinking my prints in the comment above might have something to do with it? Also running ddb locally, but the issue was occurring the cloud version as well.

Thanks,
Tom

**Comment by dchelimsky** [comment] 2019-05-06 12:06
One thing I missed the first time around is that `:CreateTable` starts the process of creating the table, but does not guarantee that it's finished in any time frame. You have to check the status of the table with something like `(aws/invoke ddb {:op :DescribeTable :request {:TableName "Forum"}})` and wait for the `:TableStatus` value to be `"ACTIVE"` before you can interact with the table. Please try def'ing the client, creating the table, then invoke `:DescribeTable` until you see "Active", and _then_ invoke `:PutItem` and report back the outcome.

**Comment by tomthought** [comment] 2019-05-07 01:06
@dchelimsky 

No dice still. 

```clojure
(let [ddb (aws/client
             (merge
              {:api :dynamodb
               :credentials-provider (credentials/profile-credentials-provider env/aws-profile)
               :region-provider (region/profile-region-provider env/aws-profile)
               :endpoint-override
               {:protocol :http
                :hostname "localhost"
                :port 8000}}))]
    (aws/invoke ddb
                {:op      :CreateTable
                 :request {:TableName             "Forum"
                           :AttributeDefinitions  [{:AttributeName "Name"
                                                    :AttributeType "S"}]
                           :KeySchema             [{:AttributeName "Name"
                                                    :KeyType       "HASH"}]
                           :ProvisionedThroughput {:ReadCapacityUnits  1
                                                   :WriteCapacityUnits 1}}})
    (while (not= "ACTIVE"
                 (-> ddb
                     (aws/invoke {:op :DescribeTable :request {:TableName "Forum"}})
                     :Table
                     :TableStatus))
      (Thread/sleep 1000))

    (aws/invoke
     ddb
     {:op :PutItem
      :request {:TableName "Forum"
                :Item {"Name" {"S" "Tom"}}}}))
;; => 
{:__type "com.amazon.coral.validate#ValidationException",
 :message
 "Supplied AttributeValue is empty, must contain exactly one of the supported datatypes",
 :cognitect.anomalies/category :cognitect.anomalies/incorrect}

```

**Comment by dchelimsky** [comment] 2019-05-07 17:19
OK, I finally reproduced this and was able to figure out what's going on. The request you're providing does not match the spec, which you can see in the output from `(aws/doc ddb :PutItem)` (with non-essential content elided):

```
-------------------------
PutItem

...

-------------------------
Request

{:ReturnItemCollectionMetrics string,
 ...
 :Item [:map-of string shape/AttributeValue],
 :ConditionalOperator string}

Required

[:TableName :Item]

-------------------------
Response

...

-------------------------
Given

{shape/AttributeValue
 {:L [:seq-of shape/AttributeValue],
  :M [:map-of string shape/AttributeValue],
  :NS [:seq-of string],
  :BOOL boolean,
  :B blob,
  :SS [:seq-of string],
  :NULL boolean,
  :S string,
  :BS [:seq-of blob],
  :N string}}
```

This tells you that `:Item` is a map of `string` to `shape/AttributeValue`, which you can see defines a map with keyword keys, not string keys. Change the `"S"` to `:S` in the `:PutItem` `:request` and it works:

``` clojure
(aws/invoke
     ddb
     {:op :PutItem
      :request {:TableName "Forum"
                :Item {"Name" {:S "Tom"}}}})
```

**Comment by dchelimsky** [comment] 2019-05-07 17:19
Sorry I didn't catch that on day 1. Got sidetracked by some red herrings.

**Comment by tomthought** [comment] 2019-05-07 22:19
Thanks for sticking with this @dchelimsky 

FWIW, there seems to be an issue with the spec validation, which is why we got this far. I had spec validation turned on and it was still passing. Seems like both variants actually end up passing the spec, so might be worth taking a look into that?

```clojure
(clojure.spec.alpha/valid?
 :cognitect.aws.dynamodb/PutItemInput
 {:TableName "Forum"
  :Item {"Name" {"S" "Tom"}}}) ;; => true

(clojure.spec.alpha/valid?
 :cognitect.aws.dynamodb/PutItemInput
 {:TableName "Forum"
  :Item {"Name" {:S "Tom"}}}) ;; => true
```

Thanks again,
Tom

**Comment by dchelimsky** [comment] 2019-05-10 14:53
That's because the spec we're generating looks like this:

```
(s/describe  :cognitect.aws.dynamodb/AttributeValue)
(keys
 :opt-un
 [:cognitect.aws.dynamodb.AttributeValue/NULL
  :cognitect.aws.dynamodb.AttributeValue/L
  :cognitect.aws.dynamodb.AttributeValue/BOOL
  :cognitect.aws.dynamodb.AttributeValue/M
  :cognitect.aws.dynamodb.AttributeValue/S
  :cognitect.aws.dynamodb.AttributeValue/B
  :cognitect.aws.dynamodb.AttributeValue/NS
  :cognitect.aws.dynamodb.AttributeValue/N
  :cognitect.aws.dynamodb.AttributeValue/BS
  :cognitect.aws.dynamodb.AttributeValue/SS])
```

It's a set of keywords representing other specs in the registry. Since specs are open the string "S" is ignored. You can see it fail if you pass `:Tom` instead of `"Tom"`:

```
(clojure.spec.alpha/valid?
 :cognitect.aws.dynamodb/PutItemInput
 {:TableName "Forum"
  :Item {"Name" {"S" :Tom}}}) ;; => true

(clojure.spec.alpha/valid?
 :cognitect.aws.dynamodb/PutItemInput
 {:TableName "Forum"
  :Item {"Name" {:S :Tom}}}) ;; => false
```

The alternative would be to have something like `(map-of #{:L :M :NS :BOOL :B :SS :NULL :S :BS :N} ¯\_(ツ)_/¯)`, where `¯\_(ツ)_/¯` is a spec that says "If the key is :S, then the value must be a `string?`, etc, but that would be a violation of the principle of open-specs.
