### ISSUE TITLE
S3 CopyObject does not work with validate requests

### ISSUE THREAD

**Issue by jsyrjala** [cognitect-labs/aws-api#102] opened 2019-11-08 06:16 UTC
## Dependencies

``` clojure
[com.cognitect.aws/api "0.8.391"],
[com.cognitect.aws/endpoints "1.1.11.664"],
[com.cognitect.aws/s3 "762.2.558.0"]
[com.cognitect.aws/lambda "746.2.533.0"],
;; Added due to https://github.com/cognitect-labs/aws-api/issues/97
[com.cognitect/http-client "0.1.101"]
```

## Description with failing test case

When doing S3 CopyObject with validate-requests set to true, the request fails with validation error,
same request works without validation. Is there an another way to specify :CopySource that the validation accepts?

`(aws/doc s3 :CopyObject)` says that `:CopySource` is a string and is a required value.

```
(aws/validate-requests s3 false)
=> false

(aws/invoke s3 {:op :CopyObject :request {:CopySource (str  bucket "/" file-key)  :Bucket bucket :Key target-key}  })
;; this successfully copies the file in S3
=> {:CopyObjectResult {:ETag "\"0c91e767494c6b3acae7e3ada695c2ca\"", :LastModified #inst"2019-11-08T05:56:57.000-00:00"}}

(aws/validate-requests s3 true)
=> true

(aws/invoke s3 {:op :CopyObject :request {:CopySource (str  bucket "/" file-key)  :Bucket bucket :Key target-key}  })
=>
{:clojure.spec.alpha/problems ({:path [:CopySource],
                                :pred :clojure.spec.alpha/unknown,
                                :val "mybucket/config/inbox/test-config.json",
                                :via [:cognitect.aws.s3/CopyObjectRequest :cognitect.aws.s3/CopySource],
                                :in [:CopySource]}),
 :clojure.spec.alpha/spec :cognitect.aws.s3/CopyObjectRequest,
 :clojure.spec.alpha/value {:CopySource "mybucket/config/inbox/test-config.json",
                            :Bucket "mybucket",
                            :Key "config/inbox/foo.json"},
 :cognitect.anomalies/category :cognitect.anomalies/incorrect}
```

Also specifying :CopySource as a string where bucket name and key are concatenated, is rather clunky. For example [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.copy_object) allows this kind of structure in addition to a string.
```
:CopySource {:Bucket "foo" :Key "bar.txt"}
```

**Comment by dchelimsky** [comment] 2019-11-08 14:49
Related: https://github.com/cognitect-labs/aws-api/issues/99

**Comment by dchelimsky** [comment] 2019-11-08 15:05
I'm closing this issue because it's a duplicate of #99.

The root problem is that [AWS's specs](https://github.com/aws/aws-sdk-js/blob/cb222fb4ba2ee6db158488014434c2e78e170390/apis/s3-2006-03-01.normal.json#L2317-L2320) say that `CopySource` should start with a slash:

```
"pattern": "\\/.+\\/.+"
```

... but the S3 service will accept strings that don't start with a slash, so it is not aligned with their own spec.

aws-api generates specs based on AWS's specs:

```
(s/def
  :cognitect.aws.s3/CopySource
  (s/with-gen #(re-matches (re-pattern "\\/.+\\/.+") %) #(gen/string)))
```

This presents a surface-level problem in which clojure.spec reports `:pred :clojure.spec.alpha/unknown`, so you have no way to know what spec is being violated without going to look at the actual spec definition, which you have to open up a jar to see. This has been reported in #99 and will be addressed there.

**Closed by dchelimsky** 2019-11-08 15:05 UTC

**Comment by dchelimsky** [comment] 2019-11-08 15:10
Side note: api-0.8.391 already depends on http-client-0.1.101, so you shouldn't need that additional dependency.

https://github.com/cognitect-labs/aws-api/blob/master/CHANGES.md#08391--2019-10-25

```
$ clj -Sdeps '{:deps {com.cognitect.aws/api {:mvn/version "0.8.391"}}}' -Spath
src:...~/.m2/repository/com/cognitect/http-client/0.1.101/http-client-0.1.101.jar:...
```

**Comment by dchelimsky** [comment] 2019-11-09 16:32
FYI:  if you upgrade to `[com.cognitect.aws/s3 "770.2.568.0"]`, you should see the regex pattern displayed at `:clojure.spec.alpha/problems :pred` of the output. At least now you have a way of seeing what the problem is and addressing it.
