### ISSUE TITLE
api.async stuck at delivering response

### ISSUE THREAD

**Issue by skrat** [cognitect-labs/aws-api#142] opened 2020-06-10 18:40 UTC
Trying out the async invoke to run in parallel, apparently it does its side effect (I'm `:PutObject` to `:s3`), but the response is never delivered to the chan, and it's stuck, with crazy CPU spin.

## Dependencies

JVM: OpenJDK (build 13.0.2+8)

``` clojure
{:deps {aysylu/loom {:mvn/version "1.0.2"}
  camel-snake-kebab {:mvn/version "0.4.0"}
  cheshire {:mvn/version "5.8.1"}
  com.cognitect.aws/api {:mvn/version "0.8.456"}
  com.cognitect.aws/endpoints {:mvn/version "1.1.11.789"}
  com.cognitect.aws/s3 {:mvn/version "799.2.682.0"}
  com.cognitect.aws/sqs {:mvn/version "770.2.568.0"}
  com.rpl/specter {:mvn/version "1.1.2"}
  commons-io/commons-io {:mvn/version "2.6"}
  environ {:mvn/version "1.2.0"}
  funcool/octet {:mvn/version "1.1.2"}
  lambdaisland/uri {:mvn/version "1.3.45"}
  org.clojure/algo.generic {:mvn/version "0.1.3"}
  org.clojure/clojure {:mvn/version "1.10.0"}
  org.clojure/data.json {:mvn/version "1.0.0"}
  org.clojure/data.xml {:mvn/version "0.2.0-alpha6"}
  org.clojure/data.zip {:mvn/version "0.1.2"}
  org.clojure/tools.cli {:mvn/version "0.4.2"}
  org.clojure/tools.logging {:mvn/version "0.4.1"}
  org.jogamp.jogl/jogl-all {:mvn/version "2.3.2"}
  thi.ng/geom {:mvn/version "1.0.0-RC3"}}}
```

## Description with failing test case

```clojure
(<!! (->> (for [i (range 3)]
            (aws.async/invoke
             (aws/client {:api :s3})
             {:op :PutObject
              :request {:Bucket "yada"
                        :Key (format "/tmp/out-project-%s.xml" i)
                        :Body "DAATAA"}}))
          (a/merge)
          (a/into [])))
```

I want to invoke multiple S3 PutObjects operations concurrently.

## Stack traces

This is when I interrupt the REPL (CPU keeps spinning even after this, so there are some stuck threads for sure):

```
1. Unhandled java.lang.InterruptedException
   (No message)

AbstractQueuedSynchronizer.java: 1040  java.util.concurrent.locks.AbstractQueuedSynchronizer/doAcquireSharedInterruptibly
AbstractQueuedSynchronizer.java: 1345  java.util.concurrent.locks.AbstractQueuedSynchronizer/acquireSharedInterruptibly
       CountDownLatch.java:  232  java.util.concurrent.CountDownLatch/await
                  core.clj: 7109  clojure.core/promise/reify
                  core.clj: 2320  clojure.core/deref
                  core.clj: 2306  clojure.core/deref
                 async.clj:  136  clojure.core.async/fn
                 async.clj:  125  clojure.core.async/fn
                      REPL:  282  xxx.yyy/eval47337
```

**Comment by dchelimsky** [comment] 2020-07-10 21:10
I don't believe this is an issue with aws-api.  You can reproduce it like this:

```clojure
(require '[clojure.core.async :as a])
(a/<!! (->> (for [i (range 3)]
              (let [c (a/promise-chan)]
                (a/>!! c i)
                c))
            (a/merge)
            (a/into [])))
```

Here's the source of the problem:

```clojure
clojure.core.async/into
([coll ch])
  Returns a channel containing the single (collection) result of the
  items taken from the channel conjoined to the supplied
  collection. ch must close before into produces a result.
nil
```

Since nothing is closing the source channels, the result if `into` won't produce any values.

This will work just fine:

```clojure
(->> (for [i (range 3)]
       (aws.async/invoke
        c
        {:op :PutObject
         :request {:Bucket "yada"
                   :Key (format "/tmp/out-project-%s.xml" i)
                   :Body "DAATAA"}}))
     (map a/<!!))
```

**Closed by dchelimsky** 2020-07-10 21:10 UTC
Labels: bug
