### ISSUE TITLE
Kinesis GetRecords fails with JSON EOF inside string error

### ISSUE THREAD

**Issue by eoliphan** [cognitect-labs/aws-api#101] opened 2019-11-01 17:48 UTC
``` clojure
[com.cognitect.aws/api "0.8.391"]
 [com.cognitect.aws/kinesis "746.2.533.0"]
 [com.cognitect.aws/endpoints "1.1.11.664"]
```

## Description with failing test case

Pretty straightforward, call GetShardIterator, use the returned iterator to call GetRecords
```
(aws/invoke ks {:op :GetRecords
                :request {:ShardIterator si
                          :Limit 10}})
```

## Stack traces

=>
{:cognitect.anomalies/category :cognitect.anomalies/fault,
 :cognitect.aws.client/throwable #error{:cause "JSON error (end-of-file inside string)",
                                        :via [{:type java.io.EOFException,
                                               :message "JSON error (end-of-file inside string)",
                                               :at [clojure.data.json$read_quoted_string invokeStatic "json.clj" 139]}],
                                        :trace [[clojure.data.json$read_quoted_string invokeStatic "json.clj" 139]
                                                [clojure.data.json$read_quoted_string invoke "json.clj" 133]
                                                [clojure.data.json$_read invokeStatic "json.clj" 195]
                                                [clojure.data.json$_read invoke "json.clj" 177]
                                                [clojure.data.json$read_object invokeStatic "json.clj" 93]
                                                [clojure.data.json$read_object invoke "json.clj" 74]
                                                [clojure.data.json$_read invokeStatic "json.clj" 220]
                                                [clojure.data.json$_read invoke "json.clj" 177]
                                                [clojure.data.json$read_array invokeStatic "json.clj" 71]
                                                [clojure.data.json$read_array invoke "json.clj" 59]
                                                [clojure.data.json$_read invokeStatic "json.clj" 223]
                                                [clojure.data.json$_read invoke "json.clj" 177]
                                                [clojure.data.json$read_object invokeStatic "json.clj" 93]
                                                [clojure.data.json$read_object invoke "json.clj" 74]
```

**Comment by dchelimsky** [comment] 2019-11-01 18:30
Please include all the steps necessary to reproduce.

**Comment by ghadishayban** [comment] 2019-11-08 20:16
Cannot reproduce this issue:

deps.edn
```
{:deps {com.cognitect.aws/api       {:mvn/version "0.8.391"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.11.664"}
        com.cognitect.aws/kinesis   {:mvn/version "746.2.533.0"}}}
```
code
```
(ns kinesis
  (:require [cognitect.aws.client.api :as aws]
            [cognitect.aws.credentials :as creds]))

(def kc (aws/client {:api :kinesis}))
(def stream "ghaditest")

(aws/invoke kc {:op :CreateStream
                :request {:StreamName stream
                          :ShardCount 1}})

;; do this a few times to drop a few messages:
(aws/invoke kc {:op :PutRecord
                :request {:StreamName stream
                          :PartitionKey "aaa"
                          :Data "nothing"}})

(def sid (-> (aws/invoke kc {:op :ListShards
                             :request {:StreamName stream}})
             (get-in [:Shards 0 :ShardId])))

(def iter (-> (aws/invoke kc {:op :GetShardIterator
                              :request {:ShardIteratorType "TRIM_HORIZON" ;; or "LATEST"
                                        :StreamName stream
                                        :ShardId sid}})
              (get :ShardIterator)))

(aws/invoke kc {:op :GetRecords
                :request {:ShardIterator iter}})
```
output of last call:
```
{:Records
 [{:SequenceNumber
   "49601209286267140649174230292844171197979345226989305858",
   :ApproximateArrivalTimestamp
   #inst "2019-11-08T20:03:20.000-00:00",
   :Data
   #object[java.io.BufferedInputStream 0x59b5c095 "java.io.BufferedInputStream@59b5c095"],
   :PartitionKey "aaa"}
  {:SequenceNumber
   "49601209286267140649174230292845380123798960062322442242",
   :ApproximateArrivalTimestamp
   #inst "2019-11-08T20:03:23.000-00:00",
   :Data
   #object[java.io.BufferedInputStream 0x2d2a7402 "java.io.BufferedInputStream@2d2a7402"],
   :PartitionKey "aaa"}
  {:SequenceNumber
   "49601209286267140649174230292846589049618574897655578626",
   :ApproximateArrivalTimestamp
   #inst "2019-11-08T20:03:26.000-00:00",
   :Data
   #object[java.io.BufferedInputStream 0x5744023b "java.io.BufferedInputStream@5744023b"],
   :PartitionKey "aaa"}],
 :NextShardIterator
 "AAAAAAAAAAEfG1I0EYYwo/wonEVPL0rCx6ap7Q6/eTrOkuMFdN3ro2VnLxAiWMUdL/Gm9Gd1FWzQhNumyfQJk4sKNhk0jT4VpAR/NcqJy7KgXj5Or6rJKZPldV90aCx5M0U3Qi6Bu2fgvJO01STq0whAy25bwZZKtsomV2+amVE7N3n6OP7TfAGOmjpdeukai6DhREy1wFif59FQMslBg/yXZJz8qAeb",
 :MillisBehindLatest 0}
```

**Comment by dchelimsky** [comment] 2019-12-30 16:13
@eoliphan I'm closing this, but please feel free to reopen this one or submit a new one once you have a repro for us.

**Closed by dchelimsky** 2019-12-30 16:13 UTC
Labels: bug, cannot reproduce
